### ISSUE TITLE
Write unit & integration tests for contributions form

### ISSUE THREAD

**Issue by zainfathoni** [zainfathoni/senar.ai#24]
## Description

Increase code coverage of the form components used in the New Contribution page.

This issue is demonstrated in this talk:

* **Software Web Testing**: [_Pengujian Perangkat Lunak Web_](https://www.facebook.com/rr17x/posts/pfbid068qzcd2tvVUKVkLrLwApbktM5hsWTrcFJuqjhybRNh2BD7YdL65Vrgy3dAD4oudLl?__cft__[0]=AZXlBEILFOeeXaOgz0LgIbAT0W0zVCwZj_flRa72RbxGNMqt4EZTl12fq0dOjg4fiWN26AwwNs1WRbldLqJaD_7s9AbyMgo6LUgsJXOc7i3R1YSyZDpOM1ISMpP5KxM4LbuptBli4ak4sIkfdUedw_jU&__tn__=%2CO%2CP-R).

## Narrative

- **As a** public visitor
- **I want** to submit an activity to the contribution form
- **so that** I can get my activity reviewed by the curators.

### Scenario 1: Successful form submission

- **Given** I visit `/contributions/new` page
- **and** I fill in the form correctly
- **when** I submit the form
- **then** I should be redirected to a `/contributions/:activityId` route
- **and** I can see my submission has been recorded correctly.

### Client

- [x] Extract the contribution form component from `/contributions/new.tsx` route.
  - [x] Ensure that the end-to-end test scenarios are not broken after the component extraction.
- [ ] Write unit & integration tests for the contribution form component, which should also cover the `form-elements.tsx` file.
  - [x] Assert form submission
  - [ ] Assert styling
     - [ ] Inline snapshot
  - [x] Make the tests easier to read by utilising [Faker](https://fakerjs.dev) and [test-data-bot](https://github.com/jackfranklin/test-data-bot)
  - [ ] Assert web accessibility
     - [x] ARIA
     - [ ] Focus Management
     - [ ] Test and improve VoiceOver Navigation
        To activate/deactivate VoiceOver, press `Fn + CMD + F5`. (On a Mac desktop keyboard, you can omit the `Fn` key.)

### Server

- [ ] Extract the FormData transformation to Activity entity
- [ ] Test the FormData transformation
- [ ] Refactor the imperative data transformation into [functional paradigm](https://www.facebook.com/gifa.eriyanto/posts/pfbid0rEKy8hR7Uq4rKLNzzRenCiGrwzRJXpXrJUoJo1kgpHq1f4h9fEuWGvNS4z8rUrMml?__tn__=%2CO*F)
- [ ] Use [zod](https://zod.dev) for data validation

**Comment by iamyuu** [comment]
Hi @zainfathoni I'm interested in working on this but in my local, the page is broken. What should I do?

<img width="1155" alt="Screen Shot 2022-10-02 at 08 31 51" src="https://user-images.githubusercontent.com/45778229/193434111-bb58e64f-8f66-4c35-99d1-a4e7a8460791.png">

**Comment by zainfathoni** [comment]
> Hi @zainfathoni I'm interested in working on this but in my local, the page is broken. What should I do?
> 
> <img alt="Screen Shot 2022-10-02 at 08 31 51" width="1155" src="https://user-images.githubusercontent.com/45778229/193434111-bb58e64f-8f66-4c35-99d1-a4e7a8460791.png">

Can you run `npm run reset:prisma` script locally? That command should prepare the local SQLite database accordingly.

**Comment by iamyuu** [comment]
fixed, thanks

**Comment by shyambh** [comment]
Hi @zainfathoni , are we maintaining tests using Playwright or can we use Cypress as well?

**Comment by zainfathoni** [comment]
> Hi @zainfathoni , are we maintaining tests using Playwright or can we use Cypress as well?

In this project, I decided to use Playwright because of its cross-browser testing compatibility. So please keep using Playwright for this project. Thanks.

**Comment by depapp** [comment]
hi @zainfathoni 
what do you think about implementing `page-object-model (POM)` pattern into this project?

reference: 
- https://martinfowler.com/bliki/PageObject.html
- https://playwright.dev/docs/pom

**Comment by shyambh** [comment]
Unfortunately, I will need to unassign myself from this issue since I am not well versed with Playwright. 
My apologies 🙏🏼

**Comment by zainfathoni** [comment]
> hi @zainfathoni 
> 
> what do you think about implementing `page-object-model (POM)` pattern into this project?
> 
> 
> 
> reference: 
> 
> - https://martinfowler.com/bliki/PageObject.html
> 
> - https://playwright.dev/docs/pom

I think that's a good idea. I've never tried it before.
Thanks for suggesting it! Feel free to raise a PR to refactor my existing end-to-end test to the Page Object Models pattern. 😁

**Comment by depapp** [comment]
> I think that's a good idea. I've never tried it before. Thanks for suggesting it! Feel free to raise a PR to refactor my existing end-to-end test to the Page Object Models pattern. 😁

noted @zainfathoni , I'll try 😁

**Comment by depapp** [comment]
hi @zainfathoni , could you please help to check https://github.com/zainfathoni/senar.ai/pull/33 
thanks

**Comment by zainfathoni** [comment]
Reopening this issue because there are still more tasks left.
